name: 'bumb-dev-version'
description: 'Action to increment the dev version of an R package in DESCRIPTION'
author: 'Dan Chaltiel'
branding:
    icon: 'hash'
    color: 'green'

inputs:
  create-tag:
    description: 'Whether a tag should be created to reference the new dev version'
    default: false

runs:
  using: "composite"
  steps:
        
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::desc

    - name: Increment dev version
      id: vars
      run: |
        invisible(desc::desc_bump_version("dev"))
        new_version = desc::desc_get_version()
        cat(sprintf("PKG_NEW_VERSION=%s\n", new_version), 
            file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        message("Setting PKG_NEW_VERSION to ", new_version)
      shell: Rscript {0}
      
    - name: Commit the version change
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Update dev version (Github Actions)'

    - name: Create the associated tag
      if: inputs.create-tag != false
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/v${{ env.PKG_NEW_VERSION }}',
            sha: context.sha
          })
          
